export const certificatesData = [
  {
    id: 1,
    title: "Desarrollo Web Responsive",
    organization: "Platzi",
    date: "Enero 2023",
    category: "Desarrollo Web",
    image: "../../assets/certificates/001.jpg",
  },
  {
    id: 2,
    title: "React Avanzado",
    organization: "Udemy",
    date: "Marzo 2023",
    category: "Frontend",
    image: "../../assets/certificates/001.jpg",
  },
  {
    id: 3,
    title: "UI/UX Design Fundamentals",
    organization: "Coursera",
    date: "Mayo 2023",
    category: "Diseño",
    image: "../../assets/certificates/001.jpg",
  },
  {
    id: 4,
    title: "JavaScript Moderno",
    organization: "freeCodeCamp",
    date: "Junio 2023",
    category: "Desarrollo Web",
    image: "../../assets/certificates/001.jpg",
  },
  {
    id: 5,
    title: "Tailwind CSS Masterclass",
    organization: "Udemy",
    date: "Agosto 2023",
    category: "Frontend",
    image: "../../assets/certificates/001.jpg",
  },
  {
    id: 6,
    title: "Node.js Backend Development",
    organization: "Platzi",
    date: "Octubre 2023",
    category: "Backend",
    image: "../../assets/certificates/001.jpg",
  },
  {
    id: 7,
    title: "Git & GitHub Professional",
    organization: "LinkedIn Learning",
    date: "Noviembre 2023",
    category: "DevOps",
    image: "/certificates/cert7.jpg",
  },
  {
    id: 8,
    title: "Figma UI Design",
    organization: "Domestika",
    date: "Diciembre 2023",
    category: "Diseño",
    image: "/certificates/cert8.jpg",
  },
  {
    id: 9,
    title: "Inglés Técnico para Desarrolladores",
    organization: "Coursera",
    date: "Enero 2024",
    category: "Habilidades Blandas",
    image: "/certificates/cert9.jpg",
  },
  {
    id: 10,
    title: "Angular Framework",
    organization: "Google Developers",
    date: "Febrero 2024",
    category: "Frontend",
    image: "/certificates/cert10.jpg",
  },
  {
    id: 11,
    title: "Vue.js Completo",
    organization: "Platzi",
    date: "Marzo 2024",
    category: "Frontend",
    image: "/certificates/cert11.jpg",
  },
  {
    id: 12,
    title: "Python para Data Science",
    organization: "DataCamp",
    date: "Abril 2024",
    category: "Data Science",
    image: "/certificates/cert12.jpg",
  },
  {
    id: 13,
    title: "Metodologías Ágiles",
    organization: "Scrum.org",
    date: "Mayo 2024",
    category: "Gestión de Proyectos",
    image: "/certificates/cert13.jpg",
  },
  {
    id: 14,
    title: "Diseño UX Avanzado",
    organization: "Adobe",
    date: "Junio 2024",
    category: "Diseño",
    image: "/certificates/cert14.jpg",
  },
  {
    id: 15,
    title: "Full Stack JavaScript",
    organization: "Udemy",
    date: "Julio 2024",
    category: "Desarrollo Web",
    image: "/certificates/cert15.jpg",
  },
];

// categorias para el filtro
export const certificateCategories = [
  "Todos",
  "Desarrollo Web",
  "Frontend",
  "Backend",
  "Diseño",
  "DevOps",
  "Data Science",
  "Gestión de Proyectos",
  "Habilidades Blandas"
];