const getCertificateImage = (id) =>
  new URL(`../../assets/certificatess/${id}.jpg`, import.meta.url).href;

export const certificatesData = [
  {
    id: 56,
    title: "Especialización en SQL",
    organization: "Netzun, San Ignacio University Miami, FL.",
    date: "Febrero 2026",
    category: "Base de datos",
    image: getCertificateImage(56),
  },
  {
    id: 55,
    title: "Especialización en Programación en R - Data Science",
    organization: "Netzun, San Ignacio University Miami, FL.",
    date: "Febrero 2026",
    category: "Programación",
    image: getCertificateImage(55),
  },
  {
    id: 54,
    title: "Especialización en HTML",
    organization: "Netzun, San Ignacio University Miami, FL.",
    date: "Setiembre 2025",
    category: "Desarrollo Web",
    image: getCertificateImage(54),
  },
  {
    id: 53,
    title: "Programación con Java Standard",
    organization: "Fundación Telefónica",
    date: "Febrero 2026",
    category: "Programación",
    image: getCertificateImage(53),
  },
  {
    id: 52,
    title: "Networking y Marketing Personal",
    organization: "Fundación Telefónica",
    date: "Noviembre 2025",
    category: "Marketing Digital",
    image: getCertificateImage(52),
  },
  {
    id: 51,
    title: "Marketing Digital",
    organization: "Fundación Telefónica",
    date: "Febrero 2026",
    category: "Marketing Digital",
    image: getCertificateImage(51),
  },
  {
    id: 50,
    title: "Analítica Web",
    organization: "Fundación Telefónica",
    date: "Febrero 2026",
    category: "Desarrollo Web",
    image: getCertificateImage(50),
  },
  {
    id: 49,
    title: "Técnico en integridad web",
    organization: "Fundación Carlos Slim - Capacitate para el empleo",
    date: "Enero 2026",
    category: "Desarrollo Web",
    image: getCertificateImage(49),
  },
  {
    id: 48,
    title: "Administrador de servidores",
    organization: "Fundación Carlos Slim - Capacitate para el empleo",
    date: "Noviembre 2025",
    category: "Soporte Técnico y Redes",
    image: getCertificateImage(48),
  },
  {
    id: 47,
    title: "Administrador de bases de datos",
    organization: "Fundación Carlos Slim - Capacitate para el empleo",
    date: "Diciembre 2025",
    category: "Base de datos",
    image: getCertificateImage(47),
  },
  {
    id: 46,
    title: "Técnico en informática (Ofimática)",
    organization: "Fundación Carlos Slim - Capacitate para el empleo",
    date: "Enero 2026",
    category: "Ofimática",
    image: getCertificateImage(46),
  },
  {
    id: 45,
    title: "Diseñador de experiencia de usuario (UX)",
    organization: "Fundación Carlos Slim - Capacitate para el empleo",
    date: "Febrero 2026",
    category: "Desarrollo Web",
    image: getCertificateImage(45),
  },
  {
    id: 44,
    title: "Fundamentos de Administración de sistemas",
    organization: "Microsoft y LinkedIn",
    date: "Noviembre 2025",
    category: "Soporte Técnico y Redes",
    image: getCertificateImage(44),
  },
  {
    id: 43,
    title: "Automatizaciones con N8N e Inteligencia Artificial",
    organization: "Raiola Networks",
    date: "Diciembre 2025",
    category: "Programación",
    image: getCertificateImage(43),
  },
  {
    id: 42,
    title: "Fundamentos profesionales de gestión de proyectos",
    organization: "Microsoft y LinkedIn",
    date: "Setiembre 2025",
    category: "Gestión de Proyectos",
    image: getCertificateImage(42),
  },
  {
    id: 41,
    title: "Cybersecurity Awareness",
    organization: "Certiprof",
    date: "Julio 2024",
    category: "Ciberseguridad",
    image: getCertificateImage(41),
  },
  {
    id: 40,
    title: "Business Intelligence Foundation",
    organization: "Certiprof",
    date: "Abril 2024",
    category: "Ciencia de Datos",
    image: getCertificateImage(40),
  },
  {
    id: 39,
    title: "Business Model Canvas Essentials",
    organization: "Certiprof",
    date: "Abril 2024",
    category: "Gestión de Proyectos",
    image: getCertificateImage(39),
  },
  {
    id: 38,
    title: "Gestión de Proyectos y Fundamentos de metodología Agile",
    organization: "Santander Open Academy",
    date: "Setiembre 2025",
    category: "Gestión de Proyectos",
    image: getCertificateImage(38),
  },
  {
    id: 37,
    title: "Gestión de reclamos en las entidades de la Administración Pública",
    organization: "ENAP",
    date: "Junio 2024",
    category: "Administración Pública",
    image: getCertificateImage(37),
  },
  {
    id: 36,
    title: "Comunicación y Colaboración en la Era Digital",
    organization: "Fundación Telefónica",
    date: "Abril 2024",
    category: "Transformación Digital",
    image: getCertificateImage(36),
  },
  {
    id: 35,
    title: "Neuromarketing",
    organization: "Fundación Telefónica",
    date: "Abril 2024",
    category: "Marketing Digital",
    image: getCertificateImage(35),
  },
  {
    id: 34,
    title: "E-Commerce",
    organization: "Fundación Telefónica",
    date: "Junio 2024",
    category: "Marketing Digital",
    image: getCertificateImage(34),
  },
  {
    id: 33,
    title: "Design Thinking",
    organization: "Fundación Telefónica",
    date: "Mayo 2024",
    category: "Habilidades Profesionales",
    image: getCertificateImage(33),
  },
  {
    id: 32,
    title: "Network Support and Security",
    organization: "Networking Academy",
    date: "Noviembre 2025",
    category: "Soporte Técnico y Redes",
    image: getCertificateImage(32),
  },
  {
    id: 31,
    title: "Alfabetización Digital",
    organization: "Fundación Telefónica",
    date: "Mayo 2024",
    category: "Transformación Digital",
    image: getCertificateImage(31),
  },
  {
    id: 30,
    title: "Growth Hacking",
    organization: "Fundación Telefónica",
    date: "Mayo 2024",
    category: "Marketing Digital",
    image: getCertificateImage(30),
  },
  {
    id: 29,
    title: "Computer Hardware Basics",
    organization: "Promoción del Empleo-Perú y  Networking Academy",
    date: "Noviembre 2025",
    category: "Soporte Técnico y Redes",
    image: getCertificateImage(29),
  },
  {
    id: 28,
    title: "Introducción a la Seguridad de la Información",
    organization: "Fundación Telefónica",
    date: "Setiembre 2025",
    category: "Ciberseguridad",
    image: getCertificateImage(28),
  },
  {
    id: 27,
    title: "Desarrollo Front-Back",
    organization: "Ministerio de Trabajo y Promoción del Empleo",
    date: "Noviembre 2025",
    category: "Programación",
    image: getCertificateImage(27),
  },
  {
    id: 26,
    title: "Gestión de Proyectos con Metodologías Ágiles y Enfoques Lean",
    organization: "Fundación Telefónica",
    date: "Agosto 2025",
    category: "Gestión de Proyectos",
    image: getCertificateImage(26),
  },
  {
    id: 25,
    title: "Power BI Intermedio-Avanzado",
    organization: "Netzun, San Ignacio University Miami, FL.",
    date: "Agosto 2025",
    category: "Ciencia de Datos",
    image: getCertificateImage(25),
  },
  {
    id: 24,
    title: "Desarrollo Front-End",
    organization: "Ministerio de Trabajo y Promoción del Empleo",
    date: "Agosto 2025",
    category: "Desarrollo Web",
    image: getCertificateImage(24),
  },
  {
    id: 23,
    title: "Fundamentos de UX",
    organization: "Fundación Telefónica",
    date: "Agosto 2025",
    category: "Desarrollo Web",
    image: getCertificateImage(23),
  },
  {
    id: 22,
    title: "Cyber Threat Management",
    organization: "Networking Academy",
    date: "Agosto 2024",
    category: "Ciberseguridad",
    image: getCertificateImage(22),
  },
  {
    id: 21,
    title: "Transformación Digital y el uso de la IA en el sector público",
    organization: "Expositor, Labotario Transformación Digital",
    date: "Noviembre 2024",
    category: "Transformación Digital",
    image: getCertificateImage(21),
  },  
  {
    id: 20,
    title: "Comunicación Efectiva",
    organization: "Santander Open Academy",
    date: "Julio 2024",
    category: "Habilidades Profesionales",
    image: getCertificateImage(20),
  },
  {
    id: 19,
    title: "Google: Inteligencia Artificial y productividad",
    organization: "Santander Open Academy",
    date: "Julio 2024",
    category: "Inteligencia Artificial",
    image: getCertificateImage(19),
  },
  {
    id: 18,
    title: "Transformación Digital",
    organization: "Santander Open Academy",
    date: "Julio 2024",
    category: "Transformación Digital",
    image: getCertificateImage(18),
  },
  {
    id: 17,
    title: "Modernización de la gestión pública",
    organization: "ENAP",
    date: "Mayo 2025",
    category: "Administración Pública",
    image: getCertificateImage(17),
  },
  {
    id: 16,
    title: "Seguridad en Internet",
    organization: "Fundación Telefónica",
    date: "Abril 2024",
    category: "Ciberseguridad",
    image: getCertificateImage(16),
  },
  {
    id: 15,
    title: "Introduction to Cybersecurity",
    organization: "Networking Academy",
    date: "Noviembre 2024",
    category: "Ciberseguridad",
    image: getCertificateImage(15),
  },
  {
    id: 14,
    title: "Fundamentos profesionales de IA generativa",
    organization: "Microsoft y LinkedIn",
    date: "Marzo 2025",
    category: "Inteligencia Artificial",
    image: getCertificateImage(14),
  },
  {
    id: 13,
    title: "Introduction to Data Science",
    organization: "Networking Academy",
    date: "Julio 2024",
    category: "Ciencia de Datos",
    image: getCertificateImage(13),
  },
  {
    id: 12,
    title: "Scrum Foundation",
    organization: "Certiprof",
    date: "Abril 2024",
    category: "Gestión de Proyectos",
    image: getCertificateImage(12),
  },
  {
    id: 11,
    title: "Generative AI",
    organization: "Certiprof",
    date: "Octubre 2024",
    category: "Inteligencia Artificial",
    image: getCertificateImage(11),
  },
  {
    id: 10,
    title: "Diseño Web con HTML5 + CSS",
    organization: "Fundación Telefónica",
    date: "Mayo 2024",
    category: "Desarrollo Web",
    image: getCertificateImage(10),
  },
  {
    id: 9,
    title: "Python Essentials 1",
    organization: "Networking Academy",
    date: "Setiembre 2023",
    category: "Programación",
    image: getCertificateImage(9),
  },
  {
    id: 8,
    title: "Marketing Digital",
    organization: "Certiprof",
    date: "Abril 2024",
    category: "Marketing Digital",
    image: getCertificateImage(8),
  },
  {
    id: 7,
    title: "Hackathon UDH 2024",
    organization: "PAISI",
    date: "Noviembre 2024",
    category: "Universidad",
    image: getCertificateImage(173),
  },
  {
    id: 6,
    title: "Gobierno y gestión de la seguridad de la información",
    organization: "Fundación Telefónica",
    date: "Mayo 2024",
    category: "Ciberseguridad",
    image: getCertificateImage(6),
  },
  {
    id: 5,
    title: "Programación con Javascript",
    organization: "Fundación Telefónica",
    date: "Mayo 2024",
    category: "Desarrollo Web",
    image: getCertificateImage(5),
  },
  {
    id: 4,
    title: "Office Intermedio",
    organization: "Fundación Telefónica",
    date: "Abril 2024",
    category: "Ofimática",
    image: getCertificateImage(4),
  },
  {
    id: 3,
    title: "Remote Work",
    organization: "Certiprof",
    date: "Abril 2024",
    category: "Habilidades Profesionales",
    image: getCertificateImage(3),
  },
  {
    id: 2,
    title: "Estructura, organización y funcionamiento del Estado Peruano",
    organization: "ENAP",
    date: "Diciembre 2024",
    category: "Administración Pública",
    image: getCertificateImage(2),
  },
  {
    id: 1,
    title: "Transformación Digital en el Perú",
    organization: "ENAP",
    date: "Diciembre 2024",
    category: "Transformación Digital",
    image: getCertificateImage(1),
  },  
];

// categorias para el filtro
export const certificateCategories = [
  "Todos",
  "Desarrollo Web",
  "Ciberseguridad",
  "Programación",
  "Gestión de Proyectos",
  "Habilidades Profesionales",
  "Administración Pública",
  "Transformación Digital",
  "Ofimática",
  "Marketing Digital",
  "Inteligencia Artificial",
  "Ciencia de Datos",
  "Soporte Técnico y Redes",
  "Universidad",
  "Base de datos"
];